# Generated by Django 4.2.3 on 2023-10-07 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                ("release_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.album"
                    ),
                ),
                ("artist", models.ManyToManyField(to="app.artist")),
                ("genre", models.ManyToManyField(to="app.genre")),
            ],
        ),
        migrations.CreateModel(
            name="Song_reference",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("platform", models.CharField(max_length=200)),
                ("url", models.CharField(max_length=200)),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.song"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Social_reference",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("platform", models.CharField(max_length=200)),
                ("url", models.CharField(max_length=200)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.artist"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("album", models.ManyToManyField(to="app.album")),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                ("artist", models.ManyToManyField(to="app.artist")),
            ],
        ),
        migrations.CreateModel(
            name="Crew",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("artist", models.ManyToManyField(to="app.artist")),
            ],
        ),
        migrations.AddField(
            model_name="album",
            name="artist",
            field=models.ManyToManyField(to="app.artist"),
        ),
    ]
